---
- name: Setup K3S server
  hosts: server
  become: true
  tasks:
    - name: Install k3s server
      shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -" 

    - name: Store Master node-token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token

    - local_action: copy content={{ token['content'] | b64decode }} dest=token
      become: false

    # - name: Output token value
    #   debug: msg="{{ token['content'] | b64decode}}"

    - name: Update k3s-server unit file
      lineinfile:
        path: /etc/systemd/system/k3s.service
        search_string: "server"
        line: "server --node-external-ip {{ groups['server'] | join('[]') }}"

    - name: Restart service k3s-server
      systemd_service:
        state: restarted
        daemon_reload: true
        name: k3s.service

    - name: Change config permissions
      shell: sudo chmod a=r /etc/rancher/k3s/k3s.yaml

- name: Setup K3S agent
  hosts: agent
  become: true
  tasks:
    - name: Set token
      set_fact:
        k3s_server_token: "{{ lookup('ansible.builtin.file', 'token') }}"

    - name: Output token value
      debug: msg="{{ groups['server'] | join('[]') }}"

    - name: Install k3s agent
      shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ groups['server'] | join('[]') }}:6443 K3S_TOKEN={{ k3s_server_token }} sh -"

    - name: Restart service k3s-agent
      systemd_service:
        state: restarted
        daemon_reload: true
        name: k3s-agent.service
  
